.TH "oxy-client" 1 "Fri Jul  6 01:45:34 UTC 2018" "version 3.0.0-dev1"
.SH NAME
oxy-client
.SH SYNOPSIS
oxy client [-DYXChmVv] <destination> <command>...
.SH DESCRIPTION
Connect to an Oxy server.
.PP
.B -L <local port forward>...
.RS
Create a local portforward
.RE

.B -R <remote port forward>...
.RS
Create a remote portforward
.RE

.B -D, --socks <socks>...
.RS
Bind a local port as a SOCKS5 proxy
.RE

.B -Y, --trusted-x-forwarding
.RS
Enable trusted X forwarding
.RE

.B -X, --x-forwarding
.RS
Enable X forwarding
.RE

.B -C, --compress
.RS
Enable ZLIB format compression of all transmitted data
.RE

.B --config
.RS
Path to configuration file (defaults to ~/.config/oxy/server.conf for servers
.RE
.RS
and ~/.config/oxy/client.conf for clients)
.RE

.B -h, --help
.RS
Prints help information
.RE

.B --knock-port <knock port>
.RS
Override port used for UDP knock
.RE

.B -m, --metacommand <metacommand>...
.RS
A command to run after the connection is established. The same commands from
.RE
.RS
the F10 prompt.
.RE

.B --tap <local[:remote]>
.RS
Connect two tap devices together. This will work if either: both sides of the
.RE
.RS
connection have root privileges (not recommended), or if the devices have been
.RE
.RS
previously created with appropriate permissions (e.g. 'ip tuntap add tap0 mode
.RE
.RS
tap user [youruser]')
.RE

.B --tcp-port <tcp port>
.RS
Override port used for TCP
.RE

.B --tun <local[:remote]>
.RS
Connect two tunnel devices together. This will work if either: both sides of
.RE
.RS
the connection have root privileges (not recommended), or if the devices have
.RE
.RS
been previously created with appropriate permissions (e.g. 'ip tuntap add tun0
.RE
.RS
mode tun user [youruser]')
.RE

.B -V, --version
.RS
Prints version information
.RE

.B -v, --verbose
.RS
Increase debugging output
.RE

.B --via <via>...
.RS
Connect to a different oxy server first, then proxy traffic through the
.RE
.RS
intermediary server.
.RE


.SH AUTHOR
Jenna Magius <pyrosim@gmail.com>
