.TH "oxy-reverse-server" 1 "Fri Jul  6 01:45:34 UTC 2018" "version 3.0.0-dev1"
.SH NAME
oxy-reverse-server
.SH SYNOPSIS
oxy reverse-server [-hVv] <destination>
.SH DESCRIPTION
Connect out to a listening client. Then, be a server.
.PP
.B --config
.RS
Path to configuration file (defaults to ~/.config/oxy/server.conf for
.RE
.RS
servers and ~/.config/oxy/client.conf for clients)
.RE

.B --forced-command <forced command>
.RS
Restrict command execution to the specified command
.RE

.B -h, --help
.RS
Prints help information
.RE

.B --knock-port <knock port>
.RS
Override port used for UDP knock
.RE

.B --multiplexer <multiplexer>
.RS
The command to attach to a terminal multiplexer. Ignored if the first
.RE
.RS
component is not an existent file, or if --no-tmux is supplied. [default:
.RE

/usr/bin/tmux new-session -A -s oxy]
.B --no-tmux
.RS
Do not use a terminal multiplexer as the default pty command
.RE

.B --tcp-port <tcp port>
.RS
Override port used for TCP
.RE

.B -V, --version
.RS
Prints version information
.RE

.B -v, --verbose
.RS
Increase debugging output
.RE


.SH AUTHOR
Jenna Magius <pyrosim@gmail.com>
