.TH "oxy-copy" 1 "Fri Jul  6 01:45:34 UTC 2018" "version 3.0.0-dev1"
.SH NAME
oxy-copy
.SH SYNOPSIS
oxy copy [-ChVv] <location>...
.SH DESCRIPTION
Copy files from any number of sources to one destination.
.PP
.B -C, --compress
.RS
Enable ZLIB format compression of all transmitted data
.RE

.B --config
.RS
Path to configuration file (defaults to ~/.config/oxy/server.conf for servers and
.RE

~/.config/oxy/client.conf for clients)
.B -h, --help
.RS
Prints help information
.RE

.B -V, --version
.RS
Prints version information
.RE

.B -v, --verbose
.RS
Increase debugging output
.RE


.SH AUTHOR
Jenna Magius <pyrosim@gmail.com>
