.TH "oxy-serve-one" 1 "Tue Jun 26 11:24:25 UTC 2018" "version 2.0.2"
.SH NAME
oxy-serve-one
.SH SYNOPSIS
oxy serve-one [-hipVv] <bind-address>
.SH DESCRIPTION
Accept a single TCP connection, then service it in the same process.
.PP
.B --client-config <client config>
.RS
Path to client.conf [default: ~/.config/oxy/client.conf]
.RE

.B --forced-command <forced command>
.RS
Restrict command execution to the specified command
.RE

.B -h, --help
.RS
Prints help information
.RE

.B -i, --identity <identity>
.RS
Use [identity] as authentication information for connecting to the remote
.RE
.RS
server. [env: OXY_IDENTITY=]
.RE

.B -p, --port <port>
.RS
The port used for TCP [default: 2600]
.RE

.B --server-config <server config>
.RS
Path to server.conf [default: ~/.config/oxy/server.conf]
.RE

.B -V, --version
.RS
Prints version information
.RE

.B -v, --verbose
.RS
Increase debugging output
.RE


.SH AUTHOR
Jenna Magius <pyrosim@gmail.com>
