.TH "oxy-guide" 1 "Tue Jun 26 11:24:25 UTC 2018" "version 2.0.2"
.SH NAME
oxy-guide
.SH SYNOPSIS
oxy guide [-hV] 
.SH DESCRIPTION
Print information to help a new user get the most out of Oxy.
.PP
.B -h, --help
.RS
Prints help information
.RE

.B -V, --version
.RS
Prints version information
.RE


.SH AUTHOR
Jenna Magius <pyrosim@gmail.com>
