.TH "oxy" 1 "Fri Jul  6 01:45:34 UTC 2018" "version 3.0.0-dev1"
.SH NAME
oxy
.SH SYNOPSIS
oxy [-hV] <client|configure|copy|guide|help|keygen|reverse-client|reverse-server|serve-one|server>
.SH "SEE ALSO"
.B oxy-client(1)
.PP
.B oxy-configure(1)
.PP
.B oxy-copy(1)
.PP
.B oxy-guide(1)
.PP
.B oxy-help(1)
.PP
.B oxy-keygen(1)
.PP
.B oxy-reverse-client(1)
.PP
.B oxy-reverse-server(1)
.PP
.B oxy-serve-one(1)
.PP
.B oxy-server(1)
.PP
.SH AUTHOR
Jenna Magius <pyrosim@gmail.com>
